artifacts:
  raw-dataset:
    path: artifacts/kaggle_dataset/Peliculas
    type: dataset
  preprocessed-data:
    path: artifacts/preprocessed_data
    type: dataset
  loader:
    path: artifacts/loader
    type: dataset
  video-classification:
    path: model/video.keras
    type: model

    
stages:
  data_ingestion:
    cmd: python src/fightClassifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/fightClassifier/components/data_ingestion.py
      - src/fightClassifier/pipeline/data_ingestion_pipeline.py
      - config/config.yaml
    outs:
      - artifacts/kaggle_dataset

  data_preprocessing:
    cmd: python src/fightClassifier/pipeline/data_preprocessing.py
    deps:
      - src/fightClassifier/components/data_ingestion.py
      - src/fightClassifier/pipeline/data_preprocessing.py
      - src/fightClassifier/components/data_preprocessing.py
      - config/config.yaml
      - artifacts/kaggle_dataset  # Add dataset as a dependency
    outs:
      - artifacts/preprocessed_data

  data_loader:
    cmd: python src/fightClassifier/pipeline/data_loader_pipeline.py
    deps:
      - src/fightClassifier/pipeline/data_preprocessing.py
      - src/fightClassifier/components/data_preprocessing.py
      - src/fightClassifier/pipeline/data_loader_pipeline.py
      - src/fightClassifier/components/data_loader.py
      - config/config.yaml
      - artifacts/preprocessed_data  # Depend on preprocessed data
    outs:
      - artifacts/loader

  model_training:
    cmd: python src/fightClassifier/pipeline/model_training_pipeline.py
    deps:
      - src/fightClassifier/pipeline/data_loader_pipeline.py
      - src/fightClassifier/components/data_loader.py
      - src/fightClassifier/pipeline/model_training_pipeline.py
      - src/fightClassifier/components/model_training.py
      - config/config.yaml
      - artifacts/loader  # Depend on data loader output
    outs:
      - artifacts/model
    params:
      - optimizer
      - data
      - training

  evaluate:
    cmd: python src/fightClassifier/pipeline/evaluate_pipeline.py
    deps:
      - src/fightClassifier/pipeline/model_training_pipeline.py
      - src/fightClassifier/components/evaluation.py
      - src/fightClassifier/pipeline/evaluate_pipeline.py
      - src/fightClassifier/components/model_training.py
      - config/config.yaml
      - artifacts/model  # Depend on trained models
    params:
      - optimizer
      - data
      - training

  mlflow_setup:
    cmd: python src/fightClassifier/pipeline/daghub_mlflow_pipeline.py
    deps:
      - src/fightClassifier/pipeline/daghub_mlflow_pipeline.py
      - src/fightClassifier/components/ml_flow.py
      - config/config.yaml
      - artifacts/model  # Depend on trained models
    params:
      - optimizer
      - data
      - training
