artifacts_root: artifacts

data_ingestion:
    kaggle_dataset_dir: artifacts/kaggle_dataset
    kaggle_dataset_name: naveenk903/movies-fight-detection-dataset

data_preprocessing:
    load_dataset_dir: artifacts/kaggle_dataset/Peliculas

model_train:
    save_model_dir: artifacts/models
    save_model_name: video.keras

mlflow_credential:
    MLFLOW: TRUE
    REPO_NAME: 'CCTV-Fight-Prediction-end-to-end-pipeline-dvc-aws-deploy'
    REPO_OWNER: 'rohitcode005'
    MLFLOW_TRACKING_URI: https://dagshub.com/rohitcode005/CCTV-Fight-Prediction-end-to-end-pipeline-dvc-aws-deploy.mlflow
    MLFLOW_TRACKING_USERNAME: rohitcode005
    MLFLOW_TRACKING_PASSWORD: 
    project_name: voilance-detection
    model_name: video-vision
    evaluation_param_path: artifacts/mlflow_data/evaluation.json
    model_param_path: artifacts/mlflow_data/model.json


