artifacts_root: artifacts

data_ingestion:
    kaggle_dataset_dir: artifacts/kaggle_dataset
    kaggle_dataset_name: naveenk903/movies-fight-detection-dataset

data_preprocessing:
    load_dataset_dir: artifacts/kaggle_dataset/Peliculas

model_train:
    save_model_dir: artifacts/models
    save_model_name: video.keras
